name: Libva Windows Build

inputs:
  system:
    description: Libva Windows Systems Support
    required: true
    default: mingw64
  architecture:
    description: Libva Supported architectures
    required: true
    default: x86_64
jobs:
  using: "composite"
  mingw64:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        pacboy: >-
          toolchain:p
          meson:p
  msvc:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install meson
  steps:
    needs: ${{inputs.system}}
    - name: Checkout LibVA
      uses: actions/checkout@v3
      
    - name: Enter DevShell
      shell: pwsh
      run: .github\workflows\EnterDevShell.ps1 ${{ inputs.architecture }}
    - name: Configure 
      run: meson setup _build -D -werror=true
    - name: Build
      run: meson compile -C _build
    - name: Install
      run: meson install -C _build
