name: Libva Windows Build

inputs:
  sys:
    description: Libva Windows Systems Support
    required: true
    default: mingw64
  architecture:
    description: Libva Supported architectures
    required: true
    default: x86_64
mingw64:
  - uses: msys2/setup-msys2@v2
    with:
    msystem: mingw64
    update: true
    pacboy: >-
      toolchain:p
      meson:p
msvc:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - run: pip install meson
runs:
  using "composite"
  steps:
    - run: echo Running system detected as ${{inputs.sys}}
